name: Build Qt Library
env:
  QT_REPO: 'https://github.com/qt/qt5.git'
  QT_BRANCH: 'dev'
  SNAPSHOT_TAG: 'qt-daily-snapshot'
  MODULE_SUBSET: 'qtbase,qtdeclarative,qtmultimedia'
  SHARED_FLAGS: -release -no-feature-testlib -no-feature-sql -no-feature-test_gui -no-feature-dtls -no-feature-calendarwidget -no-feature-jalalicalendar
    -no-feature-hijricalendar -no-feature-islamiccivilcalendar -nomake tests -nomake examples  -submodules qtbase,qtdeclarative,qtmultimedia
    -skip qtlanguageserver,qtquicktimeline,WITH_PCH -qt-zlib -qt-libjpeg -qt-libpng -no-harfbuzz -reduce-exports -no-feature-sctp -no-warnings-are-errors
    -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DQT_BUILD_TESTS_BY_DEFAULT=OFF -feature-optimize_full -DFEATURE_cxx20=ON -no-feature-imageformat_xbm
    -DFEATURE_quick_canvas=off -DFEATURE_quicktemplates2_calendar=off -DFEATURE_quick_designer=off -no-feature-imageformat_ppm
    -no-feature-imageformat_bmp -no-feature-pdf -no-feature-private_tests -no-feature-dbus -no-feature-vnc -DFEATURE_qdoc=off
    -no-feature-localserver -no-feature-udpsocket -no-feature-libproxy -no-feature-vkgen -no-feature-xml -no-feature-printsupport
    -disable-deprecated-up-to 0x070000
          
on:
  workflow_dispatch:
    inputs:
      qt_branch:
        description: 'Qt branch/tag to build'
        required: true
        default: "dev"
        type: string
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      qt_branch: ${{ steps.set-branch.outputs.qt_branch }}
    steps:
      - name: Set branch
        id: set-branch
        run: |
          if [ "${{ github.event.inputs.qt_branch }}" != "" ]; then
            echo "qt_branch=${{ github.event.inputs.qt_branch }}" >> $GITHUB_OUTPUT
          else
            echo "qt_branch=${{ env.QT_BRANCH }}" >> $GITHUB_OUTPUT
          fi

  build-windows:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false

      - name: Install dependencies
        run: choco install -y mingw

      - name: Initialize Qt submodules
        shell: cmd
        run: init-repository.bat --module-subset=${{ env.MODULE_SUBSET }}

      - name: Configure
        shell: cmd
        run: |         
          set CFLAGS=-O3 -s
          set CXXFLAGS=-O3 -s
          set "OUTPUT_DIR=%CD%\install"
          set "CC=C:\ProgramData\mingw64\mingw64\bin\gcc"
          set "CXX=C:\ProgramData\mingw64\mingw64\bin\g++"          

          mkdir build
          cd build
          
          REM  ..\configure.bat -schannel -prefix "%OUTPUT_DIR%" -${{ env.SHARED_FLAGS }}

      - name: List features
        shell: cmd
        run: configure.bat -list-features

      - name: Build Qt
        shell: cmd
        run: |
          cd build
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        shell: cmd
        run: 7z a "qt-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" .\install\*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-windows-mingw
          path: qt-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-android:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [release]
        arch: [arm64-v8a, armeabi-v7a]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      
      - name: Install dependencies
        run: choco install -y wget
      
      - name: Initialize Qt submodules
        shell: cmd
        run: init-repository.bat --module-subset=${{ env.MODULE_SUBSET }}

      - name: Download prebuilt Qt Host
        shell: cmd
        run: |
          mkdir host-qt
          cd host-qt
          set QT_ARCHIVE=qt-windows-mingw-release-dev.zip
          wget https://github.com/reg31/qt/releases/latest/download/%QT_ARCHIVE%
          7z x %QT_ARCHIVE%

      - name: Download prebuilt openssl
        shell: cmd
        run: |
          mkdir openssl
          cd openssl
          set OPENSSL_ARCHIVE=openssl-android-${{ matrix.arch }}.zip
          wget https://github.com/reg31/openssl/releases/latest/download/%OPENSSL_ARCHIVE%
          7z x %OPENSSL_ARCHIVE%
          setX OPENSSL_ROOT_DIR "%CD:\=/%" /m
          setX OPENSSL_INCLUDE_DIR "%CD:\=/%/include" /m
          setX OPENSSL_LIBRARIES "%CD:\=/%/lib" /m
          setX OPENSSL_USE_STATIC_LIBS TRUE /m
          
      - name: Configure Android Qt
        shell: cmd
        run: |
          set "OUTPUT_DIR=%CD:\=/%/install"
          set "QT_ROOT_DIR=%CD:\=/%/host-qt"
          
          mkdir build
          cd build
          
          ..\configure.bat -prefix "%OUTPUT_DIR%" -qt-host-path "%QT_ROOT_DIR%" -${{ env.SHARED_FLAGS }} ^
            -android-abis ${{ matrix.arch }} -android-ndk "%ANDROID_NDK_LATEST_HOME%" -android-sdk "%ANDROID_HOME%"
            REM -openssl -openssl-runtime            
            REM -DINPUT_openssl=linked -DINPUT_ssl=yes
            
      - name: List features
        shell: cmd
        run: configure.bat -list-features          

      - name: Build Android Qt
        shell: cmd
        run: |
          cd build
          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        shell: cmd
        run: 7z a "qt-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" .\install\*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-android-${{ matrix.arch }}
          path: qt-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-macos:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Initialize Qt submodules
        run: perl init-repository --module-subset=${{ env.MODULE_SUBSET }}
        
      - name: Configure and build
        run: |
          OUTPUT_DIR=$(pwd)/install
          mkdir -p build
          cd build
          
          ../configure -platform macx-clang -${{ env.SHARED_FLAGS }} -securetransport -prefix $OUTPUT_DIR
          ../configure -list-features

          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        run: 7z a "qt-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" ./install/*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-macos
          path: qt-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-ios:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Initialize Qt submodules
        run: perl init-repository --module-subset=${{ env.MODULE_SUBSET }}
      
      - name: Download prebuilt Qt Host
        run: |
          mkdir -p host-qt
          cd host-qt
          QT_ARCHIVE=qt-macos-release-dev.zip
          wget https://github.com/reg31/qt/releases/latest/download/$QT_ARCHIVE
          7z x $QT_ARCHIVE
        
      - name: Configure and build for iOS
        run: |
          OUTPUT_DIR=$(pwd)/install
          HOST_PATH=$(pwd)/host-qt
          mkdir -p build
          cd build
          
          ../configure -platform macx-ios-clang -${{ env.SHARED_FLAGS }} -securetransport -prefix $OUTPUT_DIR -qt-host-path $HOST_PATH
          ../configure -list-features

          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        run: 7z a "qt-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" ./install/*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-ios
          path: qt-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  release:
    needs: [setup, build-windows, build-android, build-macos, build-ios]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: qt-builds
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: "Qt Library - Build"
          fail_on_unmatched_files: false
          body: |
            Automated build of Qt ${{ needs.setup.outputs.qt_branch }} branch
            With qtbase, qtdeclarative and qtmultimedia (no FFMPEG)
            
            This build includes binaries for:
            - Windows MINGW (x64)
            - Android (armeabi-v7a, arm64-v8a)
            - iOS
            - macOS         
          files: |
            qt-builds/qt-windows-mingw/*.zip
            qt-builds/qt-android-armeabi-v7a/*.zip
            qt-builds/qt-android-arm64-v8a/*.zip
            qt-builds/qt-macos/*.zip
            qt-builds/qt-ios/*.zip
          
      - name: Cleanup repository
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
