name: Build Qt5 Library
env:
  QT_REPO: 'https://github.com/qt/qt5.git'
  QT_BRANCH: 'dev'
  SNAPSHOT_TAG: 'qt5-daily-snapshot'

on:
  workflow_dispatch:
    inputs:
      qt_branch:
        description: 'Qt branch/tag to build'
        required: true
        default: "dev"
        type: string
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      qt_branch: ${{ steps.set-branch.outputs.qt_branch }}
      qt_version: ${{ steps.get-version.outputs.qt_version }}
    steps:
      - name: Set branch
        id: set-branch
        run: |
          if [ "${{ github.event.inputs.qt_branch }}" != "" ]; then
            echo "qt_branch=${{ github.event.inputs.qt_branch }}" >> $GITHUB_OUTPUT
          else
            echo "qt_branch=${{ env.QT_BRANCH }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout Qt5
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ steps.set-branch.outputs.qt_branch }}
          fetch-depth: 0
          path: qt5-src

      - name: Get Qt version
        id: get-version
        working-directory: qt5-src
        run: |
          VERSION=$(git describe --tags --always 2>/dev/null || echo "unknown")
          echo "qt_version=$VERSION" >> $GITHUB_OUTPUT

  build-windows:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Setup RAM Disk
        uses: samypr100/setup-dev-drive@v3
        with:
          drive-size: 7GB
          workspace-copy: true
      
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            make
            zip
            git

      - name: Initialize Qt submodules
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        shell: msys2 {0}
        run: |
          git clone ${{ env.QT_REPO }} -b  ${{ env.QT_BRANCH }} .
          ./init-repository.bat --module-subset=qtbase,qtdeclarative,qtmultimedia

      - name: Configure
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        shell: msys2 {0}
        run: |          
          mkdir -p build
          cd build
          
          set CFLAGS=-O3 -s
          set CXXFLAGS=-O3 -s -std=c++20
          set "CC=C:\ProgramData\mingw64\mingw64\bin\gcc"
          set "CXX=C:\ProgramData\mingw64\mingw64\bin\g++"
          
           ../configure.bat -qt-zlib -qt-libjpeg -qt-libpng \
          -qt-freetype -no-harfbuzz -schannel -reduce-exports \
          -prefix "%CD%\..\install" -no-feature-testlib -no-feature-sql \
          -nomake tests -nomake examples \
          -submodules qtbase,qtdeclarative,qtmultimedia \
          -skip qtlanguageserver,qtquicktimeline,WITH_PCH \
          ${{ matrix.build_type == 'debug' && '-debug' || '-release' }}

      - name: Build Qt
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        shell: msys2 {0}
        run: |
          cd build
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        shell: pwsh
        run: |
          $installDir = Join-Path -Path $PWD -ChildPath "install"
          Write-Host "Packaging Qt install from: $installDir"
          Compress-Archive -Path $installDir -DestinationPath "qt5-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}.zip"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt5-windows-mingw
          path:  ${{ env.DEV_DRIVE_WORKSPACE }}/qt5-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}.zip

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [release]
        arch: [arm64-v8a, armeabi-v7a]
    steps:
      - name: Checkout Qt5
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libssl-dev

      - name: Install Qt tools
        uses: jurplel/install-qt-action@v4
        with:
          host: 'linux'
          set-env: 'true'
      
      - name: Initialize Qt submodules
        run: |
          perl init-repository --module-subset=qtbase,qtdeclarative
          
      - name: Build Android Qt
        run: |
          mkdir -p build
          cd build
          
          # Define install path
          INSTALL_PATH=$PWD/install
          echo "QT_INSTALL_DIR=$INSTALL_PATH" >> $GITHUB_ENV
          
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
          export CFLAGS="-O3"
          export CXXFLAGS="-O3 -std=c++20"
          
          ../configure -prefix $INSTALL_PATH \
            -release -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -reduce-exports \
            -nomake tests -nomake examples -no-feature-sql -skip qtlanguageserver,qtquicktimeline,WITH_PCH \
            -android-abis ${{ matrix.arch }} -android-ndk ${ANDROID_NDK_LATEST_HOME} -android-sdk ${ANDROID_HOME} \
            -platform android-clang -xplatform android-clang -submodules qtbase,qtdeclarative -qt-host-path $RUNNER_WORKSPACE
          
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        run: |
          OUTPUT_DIR="qt5-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}"
          mkdir -p "${OUTPUT_DIR}"
          cp -r "${QT_INSTALL_DIR}"/* "${OUTPUT_DIR}/"
          zip -r "${OUTPUT_DIR}.zip" "${OUTPUT_DIR}"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt5-android-${{ matrix.arch }}
          path: qt5-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}.zip

  build-macos:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt5
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Initialize Qt submodules
        run: |
          perl init-repository --module-subset=qtbase,qtdeclarative,qtmultimedia
        
      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          
          # Define install path and set it as environment variable
          INSTALL_PATH=$PWD/install
          echo "QT_INSTALL_DIR=$INSTALL_PATH" >> $GITHUB_ENV
          
          CONFIG_OPTIONS="-skip qtlanguageserver,qtquicktimeline,WITH_PCH -no-feature-sql -release -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -securetransport -reduce-exports -prefix ${INSTALL_PATH}"
          
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
          export CFLAGS="-O3"
          export CXXFLAGS="-O3 -std=c++20"
          
          ../configure -platform macx-clang -submodules qtbase,qtdeclarative,qtmultimedia $CONFIG_OPTIONS
          
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        run: |
          OUTPUT_DIR="qt5-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}"
          echo "Using QT_INSTALL_DIR: $QT_INSTALL_DIR"
          mkdir -p "${OUTPUT_DIR}"
          cp -r "${QT_INSTALL_DIR}"/* "${OUTPUT_DIR}/"
          zip -r "${OUTPUT_DIR}.zip" "${OUTPUT_DIR}"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt5-macos
          path: qt5-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}.zip

  build-ios:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt5
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false

      - name: Install Qt tools
        uses: jurplel/install-qt-action@v4
        with:
          host: 'mac'
          set-env: 'true'
          
      - name: Initialize Qt submodules
        run: |
          perl init-repository --module-subset=qtbase,qtdeclarative
      
      - name: Configure and build for iOS
        run: |
          mkdir -p build
          cd build
          
          # Define iOS install path and set it as environment variable
          INSTALL_PATH=$PWD/install
          echo "QT_INSTALL_DIR=$INSTALL_PATH" >> $GITHUB_ENV
          
          CONFIG_OPTIONS="-skip qtlanguageserver,qtquicktimeline,WITH_PCH -no-feature-sql -release -nomake tests -nomake examples -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -securetransport -reduce-exports -prefix ${INSTALL_PATH} -qt-host-path $RUNNER_WORKSPACE"
          
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
          export CFLAGS="-O3"
          export CXXFLAGS="-O3 -std=c++20"
          
          ../configure -platform macx-ios-clang -submodules qtbase,qtdeclarative $CONFIG_OPTIONS
          
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        run: |
          OUTPUT_DIR="qt5-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}"
          echo "Using QT_INSTALL_DIR: $QT_INSTALL_DIR"
          mkdir -p "${OUTPUT_DIR}"
          cp -r "${QT_INSTALL_DIR}"/* "${OUTPUT_DIR}/"
          zip -r "${OUTPUT_DIR}.zip" "${OUTPUT_DIR}"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt5-ios
          path: qt5-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_version }}.zip

  release:
    needs: [setup, build-windows, build-android, build-macos, build-ios]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: qt5-builds
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: "Qt5 Library - Build"
          if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
          body: |
            Automated build of Qt5 ${{ needs.setup.outputs.qt_version }}
            
            This build includes binaries for:
            - Windows (x64) with qtbase, qtdeclarative, qtmultimedia
            - Android (armeabi-v7a, arm64-v8a) with qtbase, qtdeclarative
            - iOS with qtbase, qtdeclarative
            - macOS with qtbase, qtdeclarative, qtmultimedia
            
            All builds compiled with -O3 optimization level using Ninja build system.
            
            **Build Date:** $(date +'%Y-%m-%d %H:%M:%S')
          files: |
            qt5-builds/qt5-windows-mingw/qt5-windows-mingw-*.zip
            qt5-builds/qt5-android-armeabi-v7a/qt5-android-*.zip
            qt5-builds/qt5-android-arm64-v8a/qt5-android-*.zip
            qt5-builds/qt5-macos/qt5-macos-*.zip
            qt5-builds/qt5-ios/qt5-ios-*.zip
          prerelease: true
          
      - name: Cleanup repository
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
          delete_prerelease_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
