name: Build Qt Library
env:
  QT_REPO: 'https://github.com/qt/qt5.git'
  QT_BRANCH: 'dev'
  SNAPSHOT_TAG: 'qt-daily-snapshot'
on:
  workflow_dispatch:
    inputs:
      qt_branch:
        description: 'Qt branch/tag to build'
        required: true
        default: "dev"
        type: string
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      qt_branch: ${{ steps.set-branch.outputs.qt_branch }}
    steps:
      - name: Set branch
        id: set-branch
        run: |
          if [ "${{ github.event.inputs.qt_branch }}" != "" ]; then
            echo "qt_branch=${{ github.event.inputs.qt_branch }}" >> $GITHUB_OUTPUT
          else
            echo "qt_branch=${{ env.QT_BRANCH }}" >> $GITHUB_OUTPUT
          fi

  build-windows:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false

      - name: Install dependencies
        run: |
          choco install -y mingw

      - name: Initialize Qt submodules
        shell: cmd
        run: |
          init-repository.bat --module-subset=qtbase,qtdeclarative,qtmultimedia

      - name: Configure
        shell: cmd
        run: |
          mkdir build
          cd build

          set CFLAGS=-O3 -s
          set CXXFLAGS=-O3 -s
          set "OUTPUT_DIR=%CD%\..\install"
          set "CC=C:\ProgramData\mingw64\mingw64\bin\gcc"
          set "CXX=C:\ProgramData\mingw64\mingw64\bin\g++"
          
          ..\configure.bat -qt-zlib -qt-libjpeg -qt-libpng ^
          -qt-freetype -no-harfbuzz -schannel -reduce-exports -prefix "%OUTPUT_DIR%" -no-feature-testlib -no-feature-sql -no-feature-test_gui -no-feature-dtls ^
          -no-feature-calendarwidget -no-feature-jalalicalendar -no-feature-hijricalendar -no-feature-islamiccivilcalendar ^
          -nomake tests -nomake examples -no-warnings-are-errors -submodules qtbase,qtdeclarative,qtmultimedia ^
          -skip qtlanguageserver,qtquicktimeline,WITH_PCH -DFEATURE_cxx20=ON -release ^
          -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DQT_BUILD_TESTS_BY_DEFAULT=OFF 

      - name: List features
        shell: cmd
        run: |
          cd build
          ..\configure.bat -list-features

      - name: Build Qt
        shell: cmd
        run: |
          cd build
          cmake --build . --parallel
          cmake --install .
          
      - name: Package artifacts
        shell: cmd
        run: |
          7z a "qt-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" .\install\*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-windows-mingw
          path: qt-windows-mingw-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-android:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [release]
        arch: [arm64-v8a, armeabi-v7a]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      
      - name: Install dependencies
        run: |
          choco install -y wget
      
      - name: Initialize Qt submodules
        shell: cmd
        run: |
          init-repository.bat --module-subset=qtbase,qtdeclarative,qtmultimedia

      - name: Download prebuilt Qt Host
        shell: cmd
        run: |
          mkdir host-qt
          cd host-qt
          set QT_ARCHIVE=qt-windows-mingw-release-dev.zip
          wget https://github.com/reg31/qt/releases/latest/download/%QT_ARCHIVE%
          7z x %QT_ARCHIVE%

      - name: Download prebuilt openssl
        shell: cmd
        run: |
          mkdir openssl
          cd openssl
          set OPENSSL_ARCHIVE=openssl-android-${{ matrix.arch }}.zip
          wget https://github.com/reg31/openssl/releases/latest/download/%OPENSSL_ARCHIVE%
          7z x %OPENSSL_ARCHIVE%
          
      - name: Configure Android Qt
        shell: cmd
        run: |
          set "OUTPUT_DIR=%CD:\=/%/install"   
          set "QT_ROOT_DIR=%CD:\=/%/host-qt"
          set "OPENSSL_DOWNLOADED=%CD:\=/%/openssl"
          
          mkdir build
          cd build

          ..\configure.bat -prefix "%OUTPUT_DIR%" -nomake examples -nomake tests -no-feature-sql -no-feature-test_gui ^
            -release -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -reduce-exports ^
            -android-abis ${{ matrix.arch }} -android-ndk "%ANDROID_NDK_LATEST_HOME%" -android-sdk "%ANDROID_HOME%" ^
            -submodules qtbase,qtdeclarative,qtmultimedia -qt-host-path "%QT_ROOT_DIR%" -feature-optimize_full -DFEATURE_cxx20=ON ^
            -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DQT_BUILD_TESTS_BY_DEFAULT=OFF -no-feature-dtls -no-feature-testlib ^
            -no-feature-calendarwidget -no-feature-jalalicalendar -no-feature-hijricalendar -no-feature-islamiccivilcalendar ^
            -skip qtlanguageserver,qtquicktimeline,WITH_PCH -no-warnings-are-errors ^
            -openssl-linked -- -DOPENSSL_ROOT_DIR="%OPENSSL_DOWNLOADED%" -DOPENSSL_USE_STATIC_LIBS=TRUE

      - name: List features
        shell: cmd
        run: |
          cd build
          ../configure.bat -list-features          

      - name: Build Android Qt
        shell: cmd
        run: |
          cd build
          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        shell: cmd
        run: |
          7z a "qt-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" .\install\*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-android-${{ matrix.arch }}
          path: qt-android-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-macos:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Initialize Qt submodules
        run: |
          perl init-repository --module-subset=qtbase,qtdeclarative,qtmultimedia
        
      - name: Configure and build
        run: |
          mkdir -p build
          cd build

          export CFLAGS="-O3"
          export CXXFLAGS="-O3"
          export CMAKE_CXX_STANDARD=20
          
          INSTALL_PATH=$PWD/install
          echo "QT_INSTALL_DIR=$INSTALL_PATH" >> $GITHUB_ENV
          
          ../configure -platform macx-clang -submodules qtbase,qtdeclarative,qtmultimedia -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DQT_BUILD_TESTS_BY_DEFAULT=OFF \
            -skip qtlanguageserver,qtquicktimeline,WITH_PCH -no-feature-sql -release -nomake tests -nomake examples -no-warnings-are-errors -no-feature-test_gui -no-feature-dtls \
            -no-feature-calendarwidget -no-feature-jalalicalendar -no-feature-hijricalendar -no-feature-islamiccivilcalendar -no-feature-testlib \
            -feature-optimize_full -DFEATURE_cxx20=ON -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -securetransport -reduce-exports -prefix "$INSTALL_PATH"

          ../configure -list-features
          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        run: |
          echo "Using QT_INSTALL_DIR: $QT_INSTALL_DIR"
          zip -r "qt-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" "$QT_INSTALL_DIR"/*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-macos
          path: qt-macos-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  build-ios:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [release]
    steps:
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: ${{ needs.setup.outputs.qt_branch }}
          fetch-depth: 0
          submodules: false
      
      - name: Initialize Qt submodules
        run: |
          perl init-repository --module-subset=qtbase,qtdeclarative,qtmultimedia
      
      - name: Download prebuilt Qt Host
        run: |
          mkdir host-qt
          cd host-qt
          QT_ARCHIVE=qt-macos-release-dev.zip
          curl -O https://github.com/reg31/qt/releases/latest/download/"$QT_ARCHIVE"
          unzip "$QT_ARCHIVE"
        
      - name: Configure and build for iOS
        run: |
          mkdir -p build
          cd build
          
          export CFLAGS="-O3"
          export CXXFLAGS="-O3"
          export CMAKE_CXX_STANDARD=20

          QT_HOST_PATH="$PWD/host-qt"
          INSTALL_PATH="$PWD/install"
          echo "QT_INSTALL_DIR=$INSTALL_PATH" >> $GITHUB_ENV
          
          ../configure -platform macx-ios-clang -submodules qtbase,qtdeclarative,qtmultimedia -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DQT_BUILD_TESTS_BY_DEFAULT=OFF \
            -skip qtlanguageserver,qtquicktimeline,WITH_PCH -no-feature-sql -release -nomake tests -nomake examples -no-warnings-are-errors \
            -no-feature-calendarwidget -no-feature-jalalicalendar -no-feature-hijricalendar -no-feature-islamiccivilcalendar -no-feature-testlib \
            -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -no-harfbuzz -securetransport -reduce-exports -no-feature-test_gui \
            -no-feature-dtls -feature-optimize_full -DFEATURE_cxx20=ON -prefix "$INSTALL_PATH" -qt-host-path "$QT_HOST_PATH"           

          ../configure -list-features
          cmake --build . --parallel
          cmake --install . --strip
          
      - name: Package artifacts
        run: |
          echo "Using QT_INSTALL_DIR: $QT_INSTALL_DIR"
          zip -r "qt-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip" "$QT_INSTALL_DIR"/*
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-ios
          path: qt-ios-${{ matrix.build_type }}-${{ needs.setup.outputs.qt_branch }}.zip

  release:
    needs: [setup, build-windows, build-android, build-macos, build-ios]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: qt-builds
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: "Qt Library - Build"
          fail_on_unmatched_files: false
          body: |
            Automated build of Qt ${{ needs.setup.outputs.qt_branch }} branch
            With qtbase, qtdeclarative and qtmultimedia (no FFMPEG)
            
            This build includes binaries for:
            - Windows MINGW (x64)
            - Android (armeabi-v7a, arm64-v8a)
            - iOS
            - macOS         
          files: |
            qt-builds/qt-windows-mingw/*.zip
            qt-builds/qt-android-armeabi-v7a/*.zip
            qt-builds/qt-android-arm64-v8a/*.zip
            qt-builds/qt-macos/*.zip
            qt-builds/qt-ios/*.zip
          
      - name: Cleanup repository
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
